# -*- coding: utf-8 -*-
"""PROJETO PY.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CdHenrccuWyZ1PjUQrc1itCxs6Mm40Lo

# Desempenho dos alunos em exames

## 1 - Leitura de dados com pandas:
"""

# importando as bibliotecas
import matplotlib.pyplot as plt
import pandas as pd

#Aluno: Jeferson da Silva Almeida - RA: 621101924

# lendo o arquivo csv
df_students = pd.read_csv('/home/Student_Performance.csv')

# exibindo informações do csv
print(df_students)

"""## 2 - Manipulação e limpeza de dados com pandas:

**COLUNAS DO DATAFRAME**: raça/etnia, nível de educação dos pais, almoço, curso  de preparação para o teste, porcentagem de matemática, porcentagem de pontuação de leitura, porcentagem de pontuação de escrita e sexo.
"""

# exibindo o cabeçalho do dataframe
df_students.head(5)

"""**TIPOS** DE **DADOS** E **DETALHES** DAS COLUNAS"""

# exibindo informações do dataframe
df_students.info()

"""**DELETANDO** A COLUNA **LUNCH**"""

#deletando a coluna lunch "almoço" do dataframe, pois não iremos utilizá-la
df_students.drop(['lunch'], axis = 1, inplace = True)  
df_students.head(5)

"""**ORDENANDO** AS **COLUNAS** POR **NÍVEL DE EDUCAÇÃO** DOS **PAIS**"""

# ordenação por level of education "educação dos pais" que frequentaram alguma escola
df_students.sort_values(by = ["parental level of education"], ascending = False)

# categorias e quantidades por level of education "educação dos pais"
df_students["parental level of education"].value_counts()

"""## 3 - Descritivo e exploração de dados com pandas (groupbys):

**AGRUPANDO** AS **MÉDIAS** DOS GRUPOS ATRAVÉS DA **RAÇA/ETNIA**
"""

# média das notas obtidas pelos alunos em matemática, leitura e escrita
df_students.groupby('race/ethnicity')['math percentage', 'reading score percentage', 'writing score percentage'].mean()

# analisando as maiores e menores notas em porcentagem matemática, porcentagem de pontuação de leitura e porcentagem de pontuação de escrita
df_students.groupby('race/ethnicity').agg({'math percentage' : ['min', 'max'], 'reading score percentage' : ['min', 'max'],  'writing score percentage' : ['min', 'max']})

"""**QUANTIDADE** DE ESTUDANTES: **MASCULINOS** E **FEMININOS** """

# quantidade de meninas e meninos
df_students.groupby('sex')['sex'].count()

# em gráfico
cores = ['#ff4e33', '#00FFFF']
df_students.sex.value_counts().plot(kind = 'pie', autopct = '%.2f%%', shadow = True, colors = cores)

"""**QUANTIDADE** DE ESTUDANTES QUE FIZERAM e NÃO FIZERAM **CURSO PREPARATÓRIO**"""

# quantidade de cursos preparatórios
df_students.groupby('test preparation course')['test preparation course'].count()

# em gráfico
cores = ['#7E33FF', '#00FF7F']
df_students['test preparation course'].value_counts().plot(kind = 'pie', autopct = '%.2f%%', shadow = True, colors = cores)

"""## 4 - Figuras que mostrem insights sobre os dados com pandas e matplotlib:

GRAFICO COM RELAÇÃO A **PORCENTAGEM DOS GRUPOS**
"""

# gerando gráficos com porcentagem nos grupos
plt.figure(figsize = (20, 10))

x = df_students['race/ethnicity'].value_counts()

plt.pie(x, labels = x.index, autopct = '%.2f%%',  shadow = True)
plt.title('Raça/Etnia')
plt.legend(loc = 'upper left')
plt.savefig('/home/grupos.png', dpi = 300)
plt.show()

"""## REFERÊNCIA

Disponível em: < https://www.kaggle.com/sonukumari47/students-performance-in-exams >
"""